from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime


# ---------------------------------------------
# HEADER + FOOTER
# ---------------------------------------------
def draw_header_footer(canvas, doc):
    canvas.saveState()

    # Header Text
    canvas.setFont('Helvetica-Bold', 11)
    canvas.setFillColor(colors.HexColor('#2563EB'))
    canvas.drawCentredString(A4[0] / 2, A4[1] - 40, "Infinity Learn by Sri Chaitanya")

    # Header Line
    canvas.setStrokeColor(colors.HexColor('#e5e7eb'))
    canvas.line(40, A4[1] - 50, A4[0] - 40, A4[1] - 50)

    # Footer Line
    canvas.line(40, 50, A4[0] - 40, 50)

    # Footer Text
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6b7280"))
    canvas.drawCentredString(A4[0] / 2, 35, "Infinity Sheets — Generated by Infinity Learn")

    # Page Number
    canvas.drawRightString(A4[0] - 40, 35, f"Page {doc.page}")

    canvas.restoreState()


# ---------------------------------------------
# LAST PAGE DISCLAIMER
# ---------------------------------------------
def draw_last_page(canvas, doc):
    draw_header_footer(canvas, doc)

    canvas.saveState()
    canvas.setFillColor(colors.HexColor("#DC2626"))
    canvas.setFont("Helvetica-Oblique", 9)

    disclaimer = "⚠ Note: This worksheet is AI-generated and may contain inaccuracies."

    canvas.drawCentredString(A4[0] / 2, 70, disclaimer)
    canvas.restoreState()


# ---------------------------------------------
# MAIN PDF GENERATOR (CORRECT SIGNATURE)
# ---------------------------------------------
def create_worksheet_pdf(
    header,
    subject,
    chapter,
    grade,
    difficulty,
    questions,
    answers,
    include_answers,
    pdf_name
):
    buffer = BytesIO()

    # Step 1: Create temp doc to count pages
    temp = SimpleDocTemplate(buffer, pagesize=A4)
    story_temp = build_story(subject, chapter, grade, difficulty, questions, answers, include_answers, pdf_name)

    temp.build(story_temp, onFirstPage=draw_header_footer, onLaterPages=draw_header_footer)
    total_pages = temp.page  # IMPORTANT

    # Step 2: Build final PDF with last-page check
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    story = build_story(subject, chapter, grade, difficulty, questions, answers, include_answers, pdf_name)

    def page_handler(canvas, doc_obj):
        if doc_obj.page == total_pages:
            draw_last_page(canvas, doc_obj)
        else:
            draw_header_footer(canvas, doc_obj)

    doc.build(story, onFirstPage=page_handler, onLaterPages=page_handler)

    buffer.seek(0)
    return buffer.getvalue()


# ---------------------------------------------
# STORY BUILDER
# ---------------------------------------------
def build_story(subject, chapter, grade, difficulty, questions, answers, include_answers, pdf_name):

    styles = getSampleStyleSheet()
    story = []

    # Title Styles
    title_style = ParagraphStyle(
        "title",
        parent=styles["Heading1"],
        fontSize=18,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#1e3a8a"),
        spaceAfter=14
    )

    subtitle_style = ParagraphStyle(
        "subtitle",
        parent=styles["Heading2"],
        fontSize=13,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#2563EB"),
        spaceAfter=24
    )

    question_style = ParagraphStyle(
        "qstyle",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )

    answer_style = ParagraphStyle(
        "astyle",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#059669"),
        spaceAfter=10
    )

    # TITLE
    story.append(Paragraph(f"{subject} — {chapter}", title_style))
    story.append(Paragraph(grade, subtitle_style))

    # SUMMARY TABLE
    summary_data = [
        ["Grade:", grade],
        ["Subject:", subject],
        ["Chapter:", chapter],
        ["Difficulty:", difficulty],
        ["Questions:", str(len(questions))],
        ["Answer Key:", "Included" if include_answers else "Not Included"],
        ["PDF Name:", pdf_name],
        ["Generated On:", datetime.now().strftime("%d %B %Y — %I:%M %p")],
    ]

    table = Table(summary_data, colWidths=[150, 350])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#E5E7EB")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(table)
    story.append(Spacer(1, 20))

    # QUESTIONS
    story.append(Paragraph("<b>Questions</b>", styles["Heading2"]))
    for i, q in enumerate(questions, 1):
        story.append(Paragraph(f"<b>Q{i}.</b> {q}", question_style))

    # ANSWERS
    if include_answers and answers:
        story.append(PageBreak())
        story.append(Paragraph("<b>Answer Key</b>", styles["Heading2"]))
        for i, ans in enumerate(answers, 1):
            story.append(Paragraph(f"<b>A{i}.</b> {ans}", answer_style))

    return story