from fpdf import FPDF
from io import BytesIO
from utils.helpers import remove_emojis

def create_worksheet_pdf(pdf_header, subject, chapter, grade, difficulty, 
                         questions_list, answers_list, include_answers):
    """Create PDF worksheet from questions and answers"""
    
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 15, 15)
    
    # Clean header text
    clean_header = remove_emojis(pdf_header)
    
    # Header
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 10, clean_header, ln=True, align="C")
    pdf.ln(2)
    
    # Title
    pdf.set_font("Arial", "B", 16)
    worksheet_title = f"{subject} - {chapter} Worksheet"
    pdf.cell(0, 10, worksheet_title, ln=True, align="C")
    pdf.ln(5)
    
    # Details
    pdf.set_font("Arial", "", 10)
    pdf.cell(90, 6, f"Grade: {grade}", border=0)
    pdf.cell(90, 6, f"Subject: {subject}", ln=True, border=0)
    pdf.cell(90, 6, f"Chapter: {chapter}", border=0)
    pdf.cell(90, 6, f"Difficulty: {difficulty}", ln=True, border=0)
    pdf.cell(90, 6, f"Total Questions: {len(questions_list)}", ln=True, border=0)
    pdf.ln(5)
    
    pdf.set_draw_color(0, 217, 255)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(8)
    
    # Questions
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, "Questions", ln=True)
    pdf.ln(3)
    
    for idx, question in enumerate(questions_list, 1):
        if pdf.get_y() > 260:
            pdf.add_page()
        
        pdf.set_font("Arial", "B", 11)
        clean_question = remove_emojis(question)
        q_text = f"Q{idx}. {clean_question}"
        pdf.multi_cell(0, 7, q_text, border=0)
        pdf.ln(4)
    
    # Answer Key
    if include_answers and answers_list:
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "Answer Key", ln=True, align="C")
        pdf.ln(5)
        
        pdf.set_draw_color(0, 217, 255)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(8)
        
        for idx, answer in enumerate(answers_list, 1):
            if pdf.get_y() > 260:
                pdf.add_page()
            
            pdf.set_font("Arial", "B", 11)
            clean_answer = remove_emojis(answer)
            a_text = f"A{idx}. {clean_answer}"
            pdf.multi_cell(0, 7, a_text, border=0)
            pdf.ln(4)
    
    # Footer on all pages
    page_count = pdf.page_no()
    for page_num in range(1, page_count + 1):
        pdf.page = page_num
        pdf.set_y(-15)
        pdf.set_font("Arial", "I", 8)
        pdf.set_text_color(128, 128, 128)
        footer_text = "Generated by Infinity Learn Sri Chaitanya"
        pdf.cell(0, 10, footer_text, align="C")
    
    # Save PDF to BytesIO
    pdf_output = BytesIO()
    pdf_bytes = pdf.output(dest='S')
    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode('latin1', errors='replace')
    pdf_output.write(pdf_bytes)
    pdf_output.seek(0)
    
    return pdf_output