from fpdf import FPDF
from io import BytesIO
from utils.helpers import remove_emojis


class WorksheetPDF(FPDF):
    """Custom PDF class with proper footer handling"""
    
    def __init__(self):
        super().__init__()
        self.footer_text = ""
    
    def footer(self):
        """Automatic footer on every page"""
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, self.footer_text, align="C")


def create_worksheet_pdf(pdf_header, subject, chapter, grade, difficulty, 
                         questions_list, answers_list, include_answers):
    """
    Create PDF worksheet - FIXED: No blank pages, proper pagination, footer positioning
    """
    
    # Use custom PDF class
    pdf = WorksheetPDF()
    pdf.footer_text = "Generated by Infinity Learn by Sri Chaitanya"
    pdf.set_auto_page_break(auto=True, margin=20)  # Increased margin for footer
    pdf.add_page()
    pdf.set_margins(15, 15, 15)
    
    # Clean header text
    clean_header = remove_emojis(pdf_header)
    
    # ==================== HEADER ====================
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 10, clean_header, ln=True, align="C")
    pdf.ln(2)
    
    # ==================== TITLE ====================
    pdf.set_font("Arial", "B", 16)
    worksheet_title = f"{subject} - {chapter} Worksheet"
    pdf.cell(0, 10, worksheet_title, ln=True, align="C")
    pdf.ln(5)
    
    # ==================== DETAILS ====================
    pdf.set_font("Arial", "", 10)
    pdf.cell(90, 6, f"Grade: {grade}", border=0)
    pdf.cell(90, 6, f"Subject: {subject}", ln=True, border=0)
    pdf.cell(90, 6, f"Chapter: {chapter}", border=0)
    pdf.cell(90, 6, f"Difficulty: {difficulty}", ln=True, border=0)
    pdf.cell(90, 6, f"Total Questions: {len(questions_list)}", ln=True, border=0)
    pdf.ln(5)
    
    # Line separator
    pdf.set_draw_color(0, 217, 255)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(8)
    
    # ==================== QUESTIONS SECTION ====================
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 8, "Questions", ln=True)
    pdf.ln(3)
    
    for idx, question in enumerate(questions_list, 1):
        # Check if we need a new page (leave 40mm for footer)
        if pdf.get_y() > 250:
            pdf.add_page()
        
        pdf.set_font("Arial", "B", 11)
        clean_question = remove_emojis(question)
        q_text = f"Q{idx}. {clean_question}"
        
        # Use multi_cell for proper text wrapping
        pdf.multi_cell(0, 7, q_text, border=0)
        pdf.ln(4)
    
    # ==================== ANSWER KEY SECTION ====================
    if include_answers and answers_list:
        # Start answer key on new page
        pdf.add_page()
        
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "Answer Key", ln=True, align="C")
        pdf.ln(5)
        
        # Line separator
        pdf.set_draw_color(0, 217, 255)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(8)
        
        for idx, answer in enumerate(answers_list, 1):
            # Check if we need a new page
            if pdf.get_y() > 250:
                pdf.add_page()
            
            pdf.set_font("Arial", "B", 11)
            clean_answer = remove_emojis(answer)
            a_text = f"A{idx}. {clean_answer}"
            
            # Use multi_cell for proper text wrapping
            pdf.multi_cell(0, 7, a_text, border=0)
            pdf.ln(4)
    
    # ==================== SAVE PDF ====================
    pdf_output = BytesIO()
    pdf_bytes = pdf.output(dest='S')
    
    # Handle encoding
    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode('latin1', errors='replace')
    
    pdf_output.write(pdf_bytes)
    pdf_output.seek(0)
    
    return pdf_output